transfer file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,11 +1,28 @@
 #!/usr/bin/env bash
 # Transfers a file from a client to a server
-if [ "$#" -lt 3 ]
+if [ "$#" -lt 4 ]
 then
     echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-elif [ "$#" -eq 3 ]
+    exit 1
+fi
+
+# assigning parameter to variables
+
+path_to_file=$1
+ip=$2
+username=$3
+path_to_ssh_keys=$4
+
+# disabling strict host key checking
+
+scp -0 "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "username@ubuntu@ip:~/"
+
+
+# checking if file transfer was succesful
+if 
+[ $? =eq 0 ]
 then
-    scp -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
-else
-    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
+	echo "FILE WAS TRANSFERED SUCCUSSFULLY"
+else 
+	echo "FILE TRANSFER FAILED"
 fi
